apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-site
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: certificate@arminjazi.com
    privateKeySecretRef:
      name: letsencrypt-prod-site
    solvers:
      - http01:
          ingress:
            class: nginx