apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      name: frontend-template
      labels:
        name: frontend
    spec:
      containers:
        - name: app
          image: tetrohed/website-frontend
          ports:
            - containerPort: 3000

          env:
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '3000'

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
