name: backend

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/backend_pr.yml'
jobs:
  build-test:

    runs-on: ubuntu-latest
    env:
      backend-working-dir: ./backend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
      working-directory: ${{env.backend-working-dir}}
    - name: spin up test environment
      run: docker-compose -f ${{env.backend-working-dir}}/docker-compose.test.yml up -d
    - name: wait for test environment
      run: curl --retry 10 --retry-connrefused http://localhost:6603/ --output curl.output
    - run: yarn test:coverage
      working-directory: ${{env.backend-working-dir}}