name: backend

on:
  pull_request:
    paths:
    - 'backend/**'
    - '.github/workflows/backend_pr.yml'

jobs:
  build-test:

    runs-on: ubuntu-latest
    env:
      backend-working-dir: ./backend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
      working-directory: ${{env.backend-working-dir}}
    - run: yarn lint
      working-directory: ${{env.backend-working-dir}}
    - name: spin up test environment
      run: docker-compose -f ${{env.backend-working-dir}}/docker-compose.test.yml up -d
    - run: yarn test:coverage
      env:
        DATABASE_ADDRESS: localhost
        DATABASE_USER: root
        DATABASE_PASSWORD: testpassword
        DATABASE_PORT: 6603
        SERVICE_PORT: 3001
        DATABASE_NAME: test_db
      working-directory: ${{env.backend-working-dir}}